- name: "add nodes"
  community.general.docker_swarm:
    state: join
    advertise_addr: "{{ inventory_hostname }}"
    join_token: "{{ hostvars['fridaym']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ "fridaym:2377" ]